pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Jawad12wq/course-jenkins-project.git'
            }
        }

        stage('Setup') {
            steps {
                dir('01-jenkins-basics') { 
                    sh "pip install -r requirements.txt"
                }
            }
        }

        stage('Test') {
            steps {
                dir('01-jenkins-basics') {
                    sh "pytest"
                }
            }
        }    

        stage('Deployment') {
            input {
                message "Do you want to proceed further?"
                ok "Yes"
            }
            steps {
                echo "Running Deployment"
            }
        } 
    }
}
